import { Box, VStack } from '@chakra-ui/react'
import Head from 'next/head'
import Featured from '../components/Featured'
import NavBar from '../components/NavBar'

// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Cafe app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <div className="highlight">

      </div>
      <Featured/>
      <div className="order">

      </div>
      

     
    </div>
  )
}
